### ISSUE TITLE
Chakra Prose using segoi UI font when it's specified to use another font. 

### ISSUE THREAD

**Issue by bonface221** [nikolovlazar/chakra-ui-prose#27]
Is there a way to add the font to the root element of the prose instead of going in the baseStyle and adding fonts individually

**Comment by bonface221** [comment]
![image](https://github.com/user-attachments/assets/50c3cdd8-bd6a-4d22-b1da-cf03cbae857a)

Intead using this?

![image](https://github.com/user-attachments/assets/75e7ca5b-bf2f-4b36-b5aa-10bbfa469eaf)

**Comment by bonface221** [comment]
Fixed by adding this
![image](https://github.com/user-attachments/assets/0ccfafca-ddb2-43c6-b104-39755e053c80)

**Comment by nikolovlazar** [comment]
Hey @bonface221. It has to go to the `baseStyle` because other variants depend on it. It's definitely a good practice to set it either there or override your theme so that change gets reflected to all the elements, plus you'll achieve consistency in the style that way. I'm glad you found the solution!
